chore(configs):update

diff --git a/dotfiles/.config/zshrc/30-autostart b/dotfiles/.config/zshrc/30-autostart
--- a/dotfiles/.config/zshrc/30-autostart
+++ b/dotfiles/.config/zshrc/30-autostart
@@ -2,3 +2,21 @@
 # AUTOSTART
 # -----------------------------------------------------
 
+# The Fuzzy Finder command
+finder() {
+    # Run the script and capture the result
+    local result=$($HOME/.config/hypr/scripts/finder)
+
+    # Check if the script told us to CD
+    if [[ "$result" == TYPE_DIR:* ]]; then
+        local target_dir="${result#TYPE_DIR:}"
+        cd "$target_dir" && ls
+    elif [[ "$result" == TYPE_FILE:* ]]; then
+    # Check if we have a file
+        ${EDITOR:-nano} "${result#TYPE_FILE:}"
+    else
+    # Return an error
+        echo "Could not read $result" >&2
+        return 1
+    fi
+}
