Merge ML4W 2.10.1

diff --git a/dotfiles/.config/zshrc/30-autostart b/dotfiles/.config/zshrc/30-autostart
--- a/dotfiles/.config/zshrc/30-autostart
+++ b/dotfiles/.config/zshrc/30-autostart
@@ -11,6 +11,13 @@ finder() {
     if [[ "$result" == TYPE_DIR:* ]]; then
         local target_dir="${result#TYPE_DIR:}"
         cd "$target_dir" && ls
+    elif [[ "$result" == TYPE_FILE:* ]]; then
+    # Check if we have a file
+        ${EDITOR:-nano} "${result#TYPE_FILE:}"
+    else
+    # Return an error
+        echo "Could not read $result" >&2
+        return 1
     fi
 }
 
@@ -18,5 +25,7 @@ finder() {
 # Fastfetch
 # -----------------------------------------------------
 if [[ $(tty) == *"pts"* ]]; then
-    fastfetch
+    if [ ! -f $HOME/.config/ml4w/settings/hide-fastfetch ]; then
+        fastfetch
+    fi
 fi
